---
title: Welcome
---

First draft of a working website documenting our work on this project.

## Documentation

- [Image Gallery and Upload Guide](image-gallery-guide.qmd) - Learn how to upload images and use the gallery features
- [Developer Documentation](development.qmd) - Technical documentation for developers working on the project
- [Creating New Lessons](lesson-creation-guide.qmd) - Guide for developers to create new lesson content

## Example Quarto runs

- [Using Quarto and SAM to process an image](https://github.com/vcu-ssg/ssg-hs-forensics-app/reports/example1.qmd) - This is the file that started it all!  Alina brought a Jupyter notebook to SSG.  Our first step was to convert it to a Quarto QMD.  This is the Quarto QMD.  Use this file as a template when wanting to run the SAM model and create quick-hit reports of cell images. It provides examples of how to load the image, process the image with SAM, and present the results in a [clean, quarto HTML report](./example1.html).


## Intro presentation

Below is the intro presentation shared by Alina.  Here a [direct link to the google slides](https://docs.google.com/presentation/d/1Dvj30uIWChAgkIMVAGFMYwBHVhdFYcJw6l3nDvWGdbM/edit?slide=id.p#slide=id.p) source.

```{=html}
<iframe 
src="https://docs.google.com/presentation/d/1Dvj30uIWChAgkIMVAGFMYwBHVhdFYcJw6l3nDvWGdbM/preview?slide=id.p"
frameborder="0" width="960" height="569" 
allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"
></iframe>
```
